// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using APIGirrafe.Data.UnitOfWork;

namespace APIGirrafe.Data.Migrations
{
    [DbContext(typeof(SqliteUnitOfWork))]
    partial class SqliteUnitOfWorkModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("APIGirrafe.Data.Entities.Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("RequestId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Header");
                });

            modelBuilder.Entity("APIGirrafe.Data.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("APIGirrafe.Data.Entities.RequestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RequestGroups");
                });

            modelBuilder.Entity("APIGirrafe.Data.Entities.Header", b =>
                {
                    b.HasOne("APIGirrafe.Data.Entities.Request")
                        .WithMany("Headers")
                        .HasForeignKey("RequestId");
                });

            modelBuilder.Entity("APIGirrafe.Data.Entities.Request", b =>
                {
                    b.HasOne("APIGirrafe.Data.Entities.RequestGroup", "Group")
                        .WithMany("Requests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
